version: "3"

tasks:
    test:
        desc: Test the app
        cmds:
        - go test -v -vet=off ./...

    build.cli:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/urls-checker-cli main.go 

    build.api:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/urls-checker-api backend/main.go

    deps:
        desc: install deps
        cmds: 
        - go get -u golang.org/x/lint/golint
        - go get -u github.com/fzipp/gocyclo/cmd/gocyclo
        - go get -u github.com/remyoudompheng/go-misc/deadcode
        - go get -u github.com/client9/misspell/cmd/misspell

    verifiers:
        desc: Run verifiers
        cmds:
        - gofmt -d .
        - $(go env GOPATH)/bin/golangci-lint run
        - $(go env GOPATH)/bin/gocyclo -over 100 .
        - $(go env GOPATH)/bin/deadcode -test $(shell go list ./...) || true
        - $(go env GOPATH)/bin/misspell -i monitord -error `find .`
        - go run honnef.co/go/tools/cmd/staticcheck -- ./...

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go
        - GOFLAGS=-mod=mod go run backend/main.go
        
    run.cli: 
        desc: Run the CLI app
        cmds:
        - GOFLAGS=-mod=mod go run main.go

    run.api: 
        desc: Run the API app
        cmds:
        - GOFLAGS=-mod=mod go run backend/main.go

    swagger.gen:
        desc: Generate Go code
        cmds:
        - GOFLAGS=-mod=mod go generate github.com/rawdaGastan/urls_checker/pkg github.com/rawdaGastan/urls_checker/pkg/swagger

    swagger.validate:
        desc: Validate swagger
        cmds:
        - swagger validate pkg/swagger/swagger.yml

    swagger.doc:
        desc: Doc for swagger
        cmds:
        - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html

    clean:
        desc: Remove all bin data files
        cmds:
        - rm ./bin/* -rf
