// Code generated by go-swagger; DO NOT EDIT.

// Package restapi urls-checker-api
//
//	HTTP server in Go with Swagger endpoints definition.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
