// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition.",
    "title": "urls-checker-api",
    "version": "0.1.0"
  },
  "paths": {
    "/site/{website}/report": {
      "get": {
        "description": "Returns the status of links inside the website!",
        "parameters": [
          {
            "type": "string",
            "description": "The name of the website to check.",
            "name": "website",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the status of links inside the website.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/UrlStatus"
              }
            }
          },
          "400": {
            "description": "Invalid website was provided."
          }
        }
      }
    }
  },
  "definitions": {
    "UrlStatus": {
      "type": "object",
      "properties": {
        "err": {
          "type": "string"
        },
        "status": {
          "type": "integer"
        },
        "url": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition.",
    "title": "urls-checker-api",
    "version": "0.1.0"
  },
  "paths": {
    "/site/{website}/report": {
      "get": {
        "description": "Returns the status of links inside the website!",
        "parameters": [
          {
            "type": "string",
            "description": "The name of the website to check.",
            "name": "website",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the status of links inside the website.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/UrlStatus"
              }
            }
          },
          "400": {
            "description": "Invalid website was provided."
          }
        }
      }
    }
  },
  "definitions": {
    "UrlStatus": {
      "type": "object",
      "properties": {
        "err": {
          "type": "string"
        },
        "status": {
          "type": "integer"
        },
        "url": {
          "type": "string"
        }
      }
    }
  }
}`))
}
