// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSiteWebsiteReportHandlerFunc turns a function with the right signature into a get site website report handler
type GetSiteWebsiteReportHandlerFunc func(GetSiteWebsiteReportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSiteWebsiteReportHandlerFunc) Handle(params GetSiteWebsiteReportParams) middleware.Responder {
	return fn(params)
}

// GetSiteWebsiteReportHandler interface for that can handle valid get site website report params
type GetSiteWebsiteReportHandler interface {
	Handle(GetSiteWebsiteReportParams) middleware.Responder
}

// NewGetSiteWebsiteReport creates a new http.Handler for the get site website report operation
func NewGetSiteWebsiteReport(ctx *middleware.Context, handler GetSiteWebsiteReportHandler) *GetSiteWebsiteReport {
	return &GetSiteWebsiteReport{Context: ctx, Handler: handler}
}

/*
	GetSiteWebsiteReport swagger:route GET /site/{website}/report getSiteWebsiteReport

Returns the status of links inside the website!
*/
type GetSiteWebsiteReport struct {
	Context *middleware.Context
	Handler GetSiteWebsiteReportHandler
}

func (o *GetSiteWebsiteReport) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSiteWebsiteReportParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
