// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCheckWebsiteHandlerFunc turns a function with the right signature into a get check website handler
type GetCheckWebsiteHandlerFunc func(GetCheckWebsiteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCheckWebsiteHandlerFunc) Handle(params GetCheckWebsiteParams) middleware.Responder {
	return fn(params)
}

// GetCheckWebsiteHandler interface for that can handle valid get check website params
type GetCheckWebsiteHandler interface {
	Handle(GetCheckWebsiteParams) middleware.Responder
}

// NewGetCheckWebsite creates a new http.Handler for the get check website operation
func NewGetCheckWebsite(ctx *middleware.Context, handler GetCheckWebsiteHandler) *GetCheckWebsite {
	return &GetCheckWebsite{Context: ctx, Handler: handler}
}

/*
	GetCheckWebsite swagger:route GET /check/{website} getCheckWebsite

Returns the status of links inside the website!
*/
type GetCheckWebsite struct {
	Context *middleware.Context
	Handler GetCheckWebsiteHandler
}

func (o *GetCheckWebsite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCheckWebsiteParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
