// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetSiteWebsiteReportParams creates a new GetSiteWebsiteReportParams object
//
// There are no default values defined in the spec.
func NewGetSiteWebsiteReportParams() GetSiteWebsiteReportParams {

	return GetSiteWebsiteReportParams{}
}

// GetSiteWebsiteReportParams contains all the bound params for the get site website report operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetSiteWebsiteReport
type GetSiteWebsiteReportParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The name of the website to check.
	  Required: true
	  In: path
	*/
	Website string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSiteWebsiteReportParams() beforehand.
func (o *GetSiteWebsiteReportParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rWebsite, rhkWebsite, _ := route.Params.GetOK("website")
	if err := o.bindWebsite(rWebsite, rhkWebsite, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindWebsite binds and validates parameter Website from path.
func (o *GetSiteWebsiteReportParams) bindWebsite(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Website = raw

	return nil
}
