consumes:
- application/json
info:
  description: HTTP server in Go with Swagger endpoints definition.
  title: urls-checker-api
  version: 0.1.0
produces:
- application/json
schemes:
- http
swagger: "2.0"

paths:
  /site/:
    get:
      description: Returns the status of links inside the website!
      parameters:
        - name: website
          in: path
          type: string
          required: true
          description: The name of the website to check.
      responses:
        200:
          description: Streams the links of a given website through a websocket
          