consumes:
- application/json
info:
  description: HTTP server in Go with Swagger endpoints definition.
  title: urls-checker-api
  version: 0.1.0
produces:
- application/json
schemes:
- http
swagger: "2.0"

paths:
  /site/{website}/report:
    get:
      description: Returns the status of links inside the website!
      parameters:
        - name: website
          in: path
          type: string
          required: true
          description: The name of the website to check.
      responses:
        200:
          description: Returns the status of links inside the website.
          schema:
            type: array
            items:
              $ref: '#/definitions/UrlStatus'
        400:
          description: Invalid website was provided.

definitions:
  UrlStatus:
    type: object
    properties:
      url:
        type: string
      err:
        type: string
      status:
        type: integer