// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// URLStatus Url status
//
// swagger:model UrlStatus
type URLStatus struct {

	// err
	Err string `json:"err,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this Url status
func (m *URLStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Url status based on context it is used
func (m *URLStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *URLStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *URLStatus) UnmarshalBinary(b []byte) error {
	var res URLStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
